#Logger configuration
logging.level.org.springframework.boot.web.embedded.tomcat=info
logging.level.com.javadefjournal=info
logging.level.org.springframework.web=info
logging.level.web=debug
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd} [%thread] %-5level %logger{36} - %msg%n
logging.file.name=logs/logfile-test.log

#Security configuration
jwt.key=${JWT_KEY:default-test-key}

# Database configuration
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=create-drop





